name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: knowledgefactory.azurecr.io
      - run: |
          docker build . -t knowledgefactory.azurecr.io/knowledgefactory:${{ github.sha }}
          docker push knowledgefactory.azurecr.io/knowledgefactory:${{ github.sha }}
